---
sidebar: sidebar 
permalink: trident-protect/trident-protect-customize-installation.html 
keywords: customize, trident Protect, resource limits, security context constraints, SCC, NetApp AutoSupport, proxy connection, helm, helm chart, helm upgrade 
summary: Passen Sie die Standardeinstellungen von Trident Protect an Ihre spezifischen Bedürfnisse an. 
---
= Trident Protect-Installation anpassen
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Standardkonfiguration von Trident Protect an die spezifischen Anforderungen Ihrer Umgebung anpassen.



== Legen Sie die Ressourcenbeschränkungen für Trident Protect-Container fest.

Sie können nach der Installation von Trident Protect eine Konfigurationsdatei verwenden, um Ressourcenlimits für Trident Protect-Container festzulegen. Durch das Festlegen von Ressourcenlimits können Sie steuern, wie viele der Clusterressourcen von Trident Protect-Operationen verbraucht werden.

.Schritte
. Erstellen Sie eine Datei mit dem Namen `resourceLimits.yaml`.
. Füllen Sie die Datei mit Ressourcenlimitierungsoptionen für Trident Protect-Container entsprechend den Anforderungen Ihrer Umgebung.
+
Die folgende Beispielkonfigurationsdatei zeigt die verfügbaren Einstellungen und enthält die Standardwerte für jedes Ressourcenlimit:

+
[source, yaml]
----
---
jobResources:
  defaults:
    limits:
      cpu: 8000m
      memory: 10000Mi
      ephemeralStorage: ""
    requests:
      cpu: 100m
      memory: 100Mi
      ephemeralStorage: ""
  resticVolumeBackup:
    limits:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
    requests:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
  resticVolumeRestore:
    limits:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
    requests:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
  kopiaVolumeBackup:
    limits:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
    requests:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
  kopiaVolumeRestore:
    limits:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
    requests:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
----
. Anwenden der Werte aus der `resourceLimits.yaml` Datei:
+
[source, console]
----
helm upgrade trident-protect -n trident-protect netapp-trident-protect/trident-protect -f resourceLimits.yaml --reuse-values
----




== Passen Sie die Einschränkungen des Sicherheitskontexts an

Sie können eine Konfigurationsdatei verwenden, um die OpenShift-Sicherheitskontextbeschränkungen (SCCs) für Trident Protect-Container nach der Installation von Trident Protect zu ändern. Diese Einschränkungen definieren Sicherheitsbeschränkungen für Pods in einem Red Hat OpenShift-Cluster.

.Schritte
. Erstellen Sie eine Datei mit dem Namen `sccconfig.yaml`.
. Fügen Sie der Datei die SCC-Option hinzu und ändern Sie die Parameter entsprechend den Anforderungen Ihrer Umgebung.
+
Das folgende Beispiel zeigt die Standardwerte der Parameter für die SCC-Option:

+
[source, yaml]
----
scc:
  create: true
  name: trident-protect-job
  priority: 1
----
+
In dieser Tabelle werden die Parameter für die SCC-Option beschrieben:

+
|===
| Parameter | Beschreibung | Standard 


| Erstellen | Legt fest, ob eine SCC-Ressource erstellt werden kann. Eine SCC-Ressource wird nur erstellt, wenn `scc.create` auf festgelegt ist `true` und der Helm-Installationsprozess eine OpenShift-Umgebung identifiziert. Wenn nicht unter OpenShift ausgeführt wird oder wenn `scc.create` auf eingestellt ist `false`, wird keine SCC-Ressource erstellt. | Richtig 


| Name | Gibt den Namen des SCC an. | Trident-Protect-Job 


| Priorität | Definiert die Priorität des SCC. SCCS mit höheren Prioritätswerten werden vor denen mit niedrigeren Werten bewertet. | 1 
|===
. Anwenden der Werte aus der `sccconfig.yaml` Datei:
+
[source, console]
----
helm upgrade trident-protect netapp-trident-protect/trident-protect -f sccconfig.yaml --reuse-values
----
+
Dadurch werden die Standardwerte durch die in der Datei angegebenen ersetzt `sccconfig.yaml`.





== Konfigurieren von NetApp AutoSupport Verbindungen für Trident Protect

Sie können die Art und Weise ändern, wie Trident Protect eine Verbindung zum NetApp -Support herstellt, um Support-Bundles hochzuladen, indem Sie einen Proxy für die Verbindung konfigurieren.  Sie können den Proxy so konfigurieren, dass er je nach Bedarf entweder eine sichere oder eine unsichere Verbindung verwendet.

[role="tabbed-block"]
====
.Konfigurieren Sie eine sichere Proxy-Verbindung
--
.Schritte
. Konfigurieren Sie eine sichere Proxy-Verbindung für Trident Protect-Support-Bundle-Uploads:
+
[source, console]
----
helm upgrade trident-protect -n trident-protect netapp-trident-protect/trident-protect --set autoSupport.proxy=http://my.proxy.url --reuse-values
----


--
.Konfigurieren Sie eine unsichere Proxy-Verbindung
--
.Schritte
. Konfigurieren Sie eine unsichere Proxy-Verbindung für Trident Protect-Support-Bundle-Uploads, die die TLS-Verifizierung überspringt:
+
[source, console]
----
helm upgrade trident-protect -n trident-protect netapp-trident-protect/trident-protect --set autoSupport.proxy=http://my.proxy.url --set autoSupport.insecure=true --reuse-values
----


--
====


== Trident Protect-Pods auf bestimmte Knoten beschränken

Mithilfe der Kubernetes-Knotenauswahlbeschränkung nodeSelector können Sie anhand der Knotenbezeichnungen steuern, welche Ihrer Knoten für die Ausführung von Trident Protect-Pods geeignet sind. Standardmäßig ist Trident Protect auf Knoten beschränkt, auf denen Linux ausgeführt wird. Sie können diese Einschränkungen je nach Ihren Bedürfnissen weiter anpassen.

.Schritte
. Erstellen Sie eine Datei mit dem Namen `nodeSelectorConfig.yaml`.
. Fügen Sie der Datei die Option nodeSelector hinzu und ändern Sie die Datei, um Knoten-Bezeichnungen hinzuzufügen oder zu ändern, um sie entsprechend den Anforderungen Ihrer Umgebung zu beschränken. Die folgende Datei enthält beispielsweise die standardmäßige OS-Beschränkung, zielt aber auch auf eine bestimmte Region und einen bestimmten App-Namen ab:
+
[source, yaml]
----
nodeSelector:
  kubernetes.io/os: linux
  region: us-west
  app.kubernetes.io/name: mysql
----
. Anwenden der Werte aus der `nodeSelectorConfig.yaml` Datei:
+
[source, console]
----
helm upgrade trident-protect -n trident-protect netapp-trident-protect/trident-protect -f nodeSelectorConfig.yaml --reuse-values
----
+
Dadurch werden die Standardbeschränkungen durch die in der Datei angegebenen ersetzt `nodeSelectorConfig.yaml`.





== Tägliche Trident Protect AutoSupport Bundle-Uploads deaktivieren

Optional können Sie die geplanten täglichen Uploads des Trident Protect AutoSupport Supportpakets deaktivieren.


NOTE: Standardmäßig erfasst Trident Protect Supportinformationen, die bei der Bearbeitung von NetApp Supportfällen hilfreich sind, darunter Protokolle, Metriken und Topologieinformationen zu Clustern und verwalteten Anwendungen.  Trident Protect sendet diese Support-Pakete täglich an NetApp .  Sie können manuelllink:trident-protect-generate-support-bundle.html["Generieren Sie ein Support-Bundle"] jederzeit.

.Schritte
. Erstellen Sie eine Datei mit dem Namen `autosupportconfig.yaml`.
. Fügen Sie der Datei die Option AutoSupport hinzu und ändern Sie die Parameter entsprechend den Anforderungen Ihrer Umgebung.
+
Das folgende Beispiel zeigt die Standardwerte der Parameter für die Option AutoSupport:

+
[source, yaml]
----
autoSupport:
  enabled: true
----
+
Wenn `autoSupport.enabled` auf eingestellt ist `false`, werden tägliche Uploads von AutoSupport Support-Paketen deaktiviert.

. Anwenden der Werte aus der `autosupportconfig.yaml` Datei:
+
[source, console]
----
helm upgrade trident-protect netapp-trident-protect/trident-protect -f autosupportconfig.yaml --reuse-values
----

